README.md
This change ensures when the readme is processed on pypi or anywhere else the links would work properly
=> fix(readme): fix readme links to full URLs

descope/auth.py, descope/descope_client.py, poetry.lock
fix the jet response object returned during validate_session_request so it will now include the adjusted permissions,roles,projectID,userID fields (so it will be just the same as returned from verify_code)
=> fix the jet response object returned during validate_session_request

.github/workflows/python-pr.yaml, poetry.lock
Removing the ` | tee` that resulted in the command always returning 0 so failed tests did not fail the build.
=> fix: use cov xml file for result

.gitignore, descope/__init__.py, descope/authmethod/otp.py, descope/descope_client.py, descope/management/common.py, descope/management/sso_settings.py, descope/management/tenant.py, descope/management/user.py, descope/mgmt.py, samples/management_sso_sample_app.py, samples/management_tenant_sample_app.py, samples/management_user_sample_app.py, tests/management/test_sso_settings.py, tests/management/test_tenant.py, tests/management/test_user.py
https://github.com/descope/etc/issues/806
This PR adds management capabilities to the SDK, allowing Descopers to manage tenants, users and SSO setting in a secure fashion.
=> Management

descope/auth.py, tests/test_auth.py
Add issuer support as url, support also projectID alone for backward.
=> Add issuer support as url

descope/management/common.py, descope/management/user.py, samples/management_user_sample_app.py, tests/management/test_user.py
https://github.com/descope/etc/issues/1040
Add the ability to load a single user, or search for multiple users with optional tenant and role filters.
=> Add load user and search all users

descope/__init__.py, descope/management/common.py, descope/management/sso_settings.py, samples/management_sso_sample_app.py, tests/management/test_sso_settings.py
https://github.com/descope/etc/issues/1040
Use the new `mapping` endpoint that allows role mapping as  well as user attribute mapping for an SSO IDP.
=> Use new mapping endpoint instead of deprecated role mapping

README.md, descope/management/user.py, tests/management/test_user.py
Add the ability to load a user by JWT subject.
=> Add load_by_jwt_subject to management API

README.md
Updated readme to fix fix typos in the roles and permission management examples
https://github.com/descope/etc/issues/1865
=> Updated readme to fix fix typos in the roles and permission management examples

descope/authmethod/otp.py, poetry.lock, tests/test_enchantedlink.py, tests/test_magiclink.py, tests/test_otp.py, tests/test_totp.py
Fix OTP sign in function so it will forward the refresh_token parameter to do_post function in the right place.
Added tests for all missing auth methods to validate refresh token used (if provided) and forward on the right place.
=> fix otp signin function to use refresh pramater as the right argument to do_post

README.md, descope/management/user.py, tests/management/test_user.py
Add the ability to paginate the search user response. If not explicitly set, `page` defaults to `0` (the first page).
=> Add page to search users

README.md, descope/auth.py, descope/management/common.py, descope/management/user.py, tests/management/test_user.py, tests/test_auth.py
Add support for test user:
- Create user for test
- Delete all test users
- Generate access (code and link) for test user
Related to: https://github.com/descope/etc/issues/1918
=> Add support for test user

.flake8, descope/auth.py, descope/descope_client.py, tests/test_auth.py, tests/test_descope_client.py
Aligned the return value structure of `validate_session`, `validate_and_refresh_session` to be in unified structure and fix userId and projectId property on the dict response to have the correct values (instead of empty).
Note: for backward compatibility reason we keep these claims `[amr, drn, exp, iss, rexp, sub, jwt]` on the dict response top-level and its recommended to use them from the `sessionToken` key in the dict response object.
=> Aligned validate_session, validate_and_refresh_session functions response structure

poetry.lock, pyproject.toml, renovate.json
Expand dependency ranges to increase compatibility
Enabling lockfile maintenance (with automerge) for renovate ensures a PR is opened every time there's a dependency release, to ensure tests pass with every dependency update - while allowing people who use this SDK to have a wide range
=> chore(deps): expand acceptable dependency ranges

descope/auth.py, descope/descope_client.py, tests/test_descope_client.py
Fix cases when there is a time machine glitch between the time jwt was invoked and the time when it validated,
example for this is case where getting this error: 
`jwt.exceptions.ImmatureSignatureError: The token is not yet valid (iat)`
that means that jwt was invoked before the current time on the machine.
=> Set default of 5sec to jwt validation leeway (and also make it configurable)

README.md, descope/descope_client.py, tests/test_descope_client.py
https://github.com/descope/etc/issues/3104
Ensure that the user is associated to tenant before checking roles/permissions
also added instructions for running tests locally
=> Check associated tenant

descope/__init__.py, descope/auth.py, tests/__init__.py, tests/test_auth.py
Fix the error message field (in AuthException) so it will include the full Descope error information.
=> Fix AuthException message field format so it will include the full Descope-error object

README.md, descope/management/sso_settings.py, samples/management/sso_sample_app.py, tests/management/test_sso_settings.py
- Adds the missing `redirect_url` and `domain` parameters to the `configure_via_metadata` function.
- The `redirect_url` and `domain` parameters are now required in both `configure_via_metadata` and `configure` functions.
- When calling these functions you can either pass a valid `redirect_url` / `domain` as the parameter value, or an empty string to reset whatever's currently set.
- This is a minor **_BREAKING CHANGE_** in that some function signatures have changed:
- Existing calls to `configure_via_metadata` will miss the two new parameters – pass a string value for them as explained above.
- Existing calls to `configure` might miss the parameters which had a default `None` value – pass an empty `string` to keep the same behavior.
=> Support domain and redirectURL field when updating SSO metadata URL

.github/workflows/ci.yml
fixes an issue where scheduled workflows fail on coverage, remove this job as it's not needed for scheduled checks
=> fix(ci): do not run coverage on schedule workflows

.pre-commit-config.yaml, .vscode/extensions.json, .vscode/settings.json, README.md, descope/flask/__init__.py, poetry.lock, pyproject.toml, requirements.txt, samples/flask_authentication.py, samples/magiclink_web_sample_app.py, samples/oauth_web_sample_app.py, samples/otp_web_sample_app.py, samples/password_web_sample_app.py
Fixes https://github.com/descope/etc/issues/2539
Making flask an extra package of descope python-sdk
Extra means it is not installed by default, and only when adding the extra flag it will also install Flask dependencies that are needed.
* Adjusted the sample scripts to work with the package itself
* Added typing annotations
* Reduced test coverage of the new code
* Also added vscode settings and recommended extensions for ease development 
* Removed tox from pre-commit as it's a huge overhead for every commit, devs should test locally before committing, and tests still run in CI still.
=> feat(flask): adding flask decorators as a package extra

descope/auth.py, tests/test_auth.py
Fixes https://github.com/descope/etc/issues/4322
Allow using only env vars for configuration
=> fix: allow getting project_id from env

README.md, descope/auth.py, descope/common.py, descope/descope_client.py, descope/management/common.py, descope/management/user.py, tests/management/test_user.py, tests/test_descope_client.py
Fixes https://github.com/descope/etc/issues/4713
Add user history support for auth and mgmt apis.
=> Add user history support for auth and mgmt apis

README.md, descope/management/sso_settings.py, tests/management/test_sso_settings.py
Remove redundant redirectUrl function parameter so it will not be confused with the same redirectUrl parameter inside the OIDCSettings parameter.
=> Remove redundant redirectUrl param

README.md, descope/management/common.py, descope/management/jwt.py, tests/management/test_jwt.py
+ test 
related to https://github.com/descope/etc/issues/5584
=> Add option to impersonate on management sdk

README.md, descope/management/authz.py, descope/management/common.py, descope/management/role.py, tests/management/test_role.py
Search roles based on given filter parameters
=> Search roles

descope/management/user.py, tests/management/test_user.py
Related to https://github.com/descope/etc/issues/6852
Support forcing refresh token in get provider token
Support getting the refresh token as part of the get provider token response
=> Add force refresh and get refresh token options in get provider token

README.md, descope/management/access_key.py, tests/management/test_access_key.py
Related https://github.com/descope/etc/issues/6938
Adding the description field to accessKey (create and update).
=> add description field to accessKey

descope/management/audit.py
Fix timestamps (to be integers) in Audit Search API
Related to https://github.com/descope/etc/issues/7227
=> Fix timestamps in Audit Search API

README.md, descope/common.py, descope/descope_client.py, tests/test_descope_client.py
+ test 
related to https://github.com/descope/etc/issues/7070
=> Get my tenants

.vscode/settings.json, descope/common.py, tests/test_enchantedlink.py
https://github.com/descope/etc/issues/8242
Add the revoke_other_sessions attribute in login_options.
=> Add the revoke_other_sessions attribute in login_options

README.md, descope/management/common.py, descope/management/user.py, tests/management/test_user.py
Adjust CreateTestUser endpoint url + Add SearchAllTest api for searching only test users
=> Add test user apis

descope/management/common.py
Updates the version for the Management User Add Tenant Roles API. 
With this new version, roles will be added to the tenant even if the user does not have access to the tenant. Access to the tenant will be added.
=> Management User Add Tenant Roles API upgrade

descope/authmethod/enchantedlink.py, descope/authmethod/magiclink.py, descope/authmethod/otp.py, descope/common.py, tests/test_enchantedlink.py, tests/test_magiclink.py, tests/test_otp.py
https://github.com/descope/go-sdk/pull/464
- Add support for custom `template_id` in sign up and sign in operations to choose a different messaging template other than the default one when a custom provider is configured.
=> Add support for overriding messaging template in magic link, enchanted link, and OTP messages

descope/management/user.py, tests/management/test_user.py
+ test 
related to https://github.com/descope/etc/issues/8535
=> Invite template id

descope/management/jwt.py, tests/management/test_jwt.py
Supported as part of jwt update flow
+test
fixes https://github.com/descope/etc/issues/8900
=> Allow updating jwt expiry via SDK

.vscode/settings.json, descope/management/common.py, descope/management/user.py, tests/management/test_user.py
+ tests 
related to https://github.com/descope/etc/issues/9344
=> Remove TOTP seed of a user

.vscode/settings.json, descope/auth.py, tests/management/test_user.py, tests/test_auth.py
Fixes https://github.com/descope/python-sdk/issues/490
Fix rate limit parsing when response's body is empty.
=> Fix rate limit parsing when response's body is empty

descope/management/jwt.py, tests/management/test_jwt.py
related <> 
https://github.com/descope/python-sdk/pull/478
fix update jwt optional param default value
add test
=> Update jwt refresh duration default param fix

.vscode/settings.json, descope/management/common.py, descope/management/jwt.py, tests/management/test_jwt.py
+ test 
related to https://github.com/descope/etc/issues/9497
=> Anonymous users

descope/management/common.py, descope/management/fga.py, tests/management/test_fga.py
Required for: https://github.com/descope/etc/issues/9671
Depends on: https://github.com/descope/managementservice/pull/2083
Adding support for Save & Load FGA Resources Details MGMT APIs
=> feat: adding Save/Load FGA Resources Details MGMT APIs

descope/management/common.py, descope/management/jwt.py, tests/management/test_jwt.py
related to https://github.com/descope/etc/issues/9294
+ tests
=> Stop impersonation call

descope/auth.py, tests/test_descope_client.py
Just split the exceptions handling for returning clearer error messages
=> Adjust jwt expiry error messages
