descope/python-sdk

- descope/auth.py
- descope/authmethod/magiclink.py
- descope/authmethod/oauth.py
- descope/authmethod/otp.py
- descope/authmethod/saml.py
- descope/authmethod/totp.py
- descope/authmethod/webauthn.py
- descope/common.py
- poetry.lock
- tests/test_magiclink.py
- tests/test_oauth.py
- tests/test_saml.py
- tests/test_webauthn.py
related to related to https://github.com/descope/etc/issues/578
+ tests 
Also added a sample app that dos step up with custom claims
> Extend API to support custom claims

- descope/auth.py
- tests/common.py
- tests/test_magiclink.py
- tests/test_oauth.py
- tests/test_saml.py
- tests/test_totp.py
- tests/test_webauthn.py
Add useful headers to each request
> Add useful headers

- descope/auth.py
- descope/authmethod/magiclink.py
- descope/authmethod/oauth.py
- descope/authmethod/otp.py
- descope/authmethod/saml.py
- descope/authmethod/webauthn.py
- poetry.lock
- samples/stepup_sample_app.py
- tests/test_magiclink.py
- tests/test_oauth.py
- tests/test_saml.py
- tests/test_webauthn.py
Move login options to start of authentication flows
+ tests
related to https://github.com/descope/etc/issues/578
> Stepup take 2

- descope/auth.py
- descope/descope_client.py
- samples/access_key_sample_app.py
- tests/test_auth.py
- tests/test_descope_client.py
Related to https://github.com/descope/etc/issues/739
> Adjust jwt response for access key with authz

- descope/common.py
- descope/descope_client.py
- tests/test_descope_client.py
Add both logout and logout_all as options
> Have both logout and logout_all as optinos

- descope/authmethod/magiclink.py
- descope/authmethod/oauth.py
- descope/authmethod/otp.py
- descope/authmethod/saml.py
- descope/authmethod/totp.py
- descope/authmethod/webauthn.py
- descope/common.py
- tests/test_magiclink.py
- tests/test_oauth.py
- tests/test_otp.py
- tests/test_saml.py
- tests/test_totp.py
- tests/test_webauthn.py
related https://github.com/descope/etc/issues/943
+ test 
Also removed verification on oauth provider, so it will be easier to add support for new oauth providers without changing SDKs
> Add MFA support

- descope/authmethod/enchantedlink.py
- descope/authmethod/magiclink.py
- descope/common.py
- descope/descope_client.py
- requirements.txt
- samples/enchantedlink_sample_app.py
- tests/test_enchantedlink.py
- tests/test_magiclink.py
+ tests 
Remove support from cross device
related to https://github.com/descope/etc/issues/1014
> Enchanted link support

- poetry.lock
- pyproject.toml
> update poetry lockfile

- descope/management/common.py
- descope/management/role.py
- descope/mgmt.py
- samples/management_permission_sample_app.py
- samples/management_role_sample_app.py
- tests/management/test_role.py
Add the ability to manage roles in a project.
> Add role API

- README.md
- descope/authmethod/otp.py
- descope/authmethod/totp.py
- descope/authmethod/webauthn.py
- descope/descope_client.py
- samples/totp_sample_app.py
- tests/test_webauthn.py
- Add missing auth methods to README
- fix typos
- add TOTP function docs
> Add missing auth methods to README, fix typos and add TOTP function docs

- README.md
Minor typo and rephrasing fixes in the README
> Minor typo and rephrasing fixes

- README.md
- descope/management/group.py
- descope/management/user.py
- samples/management/group_sample_app.py
- tests/management/test_group.py
- tests/management/test_user.py
> Rename JWT subject to user ID

- README.md
- descope/auth.py
- descope/authmethod/enchantedlink.py
- descope/authmethod/magiclink.py
- descope/authmethod/otp.py
- descope/authmethod/totp.py
- descope/authmethod/webauthn.py
- descope/descope_client.py
- descope/management/group.py
- descope/management/user.py
- samples/enchantedlink_sample_app.py
- samples/magiclink_sample_app.py
- samples/management/group_sample_app.py
- samples/management/user_sample_app.py
- samples/otp_sample_app.py
- samples/stepup_sample_app.py
- samples/templates/webauthn_demo.html
- samples/totp_sample_app.py
- samples/webauthn_web_sample_app.py
- tests/management/test_group.py
- tests/management/test_user.py
- tests/test_auth.py
- tests/test_enchantedlink.py
- tests/test_magiclink.py
- tests/test_oauth.py
- tests/test_otp.py
- tests/test_saml.py
- tests/test_totp.py
- tests/test_webauthn.py
Use login ID instead of external ID or identifier everywhere.
> Use login ID instead of external ID or identifier everywhere

- descope/authmethod/enchantedlink.py
Fix error print (login ID rename leftover)
> Fix error print

- README.md
- descope/management/sso_settings.py
- Add logout functions to README
- Fix documentation
> Add logout functions to README

- descope/__init__.py
- descope/auth.py
- descope/authmethod/enchantedlink.py
- descope/authmethod/magiclink.py
- descope/authmethod/oauth.py
- descope/authmethod/otp.py
- descope/authmethod/saml.py
- descope/authmethod/totp.py
- descope/authmethod/webauthn.py
- descope/common.py
- poetry.lock
- requirements.txt
- samples/decorators/flask_decorators.py
- samples/stepup_sample_app.py
- tests/test_auth.py
- tests/test_magiclink.py
- tests/test_oauth.py
- tests/test_otp.py
Aligned name and conventions for LoginOptions and refreshToken parameters to be snake case like all the other parameters,
Change the Delivery method enum name to SMS instead of Phone (to be aligned with all other Descope sdks)
> Aligned name and conventions

- samples/decorators/flask_decorators.py
- samples/otp_web_sample_app.py
Fixes https://github.com/descope/etc/issues/1853
> feat: set SameSite to Strict

- README.md
- descope/descope_client.py
Return the parsed JWT response from validate_session
> Return the parsed JWT response from validate_session

- README.md
- descope/management/common.py
- descope/management/sso_settings.py
- tests/management/test_sso_settings.py
Upgrade management SSO configuration to v2, which now supports the `domain` parameter.
> Upgrade management sso configuration to v2

- descope/management/common.py
- descope/management/sso_settings.py
- tests/management/test_sso_settings.py
Revert sso endpoint back to v1
> Revert sso endpoint back to v1

- README.md
- descope/management/user.py
- tests/management/test_user.py
Add the ability to invite users via the management functions.
> Add the ability to invite users

- README.md
Fixes <link_to_github_issue>
| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |
A few sentences describing the overall goals of the pull request's commits.
> fixed trailing comma in new Manage JWTs section.

- README.md
- descope/auth.py
- descope/authmethod/enchantedlink.py
- descope/authmethod/magiclink.py
- descope/authmethod/otp.py
- poetry.lock
- samples/enchantedlink_sample_app.py
- samples/magiclink_sample_app.py
- samples/otp_sample_app.py
- tests/test_magiclink.py
- tests/test_otp.py
This applies to otp magic link and enchanted link
Use of magic link and otp will break compilation upon upgrading to this version The value is returned upon initiation of the signup/in method and returned in masked format
> Return the masked email or address to caller

- README.md
- descope/authmethod/magiclink.py
- descope/authmethod/password.py
- descope/common.py
- descope/descope_client.py
- samples/password_sample_app.py
- samples/password_web_sample_app.py
- tests/test_password.py
> Add password functions

- samples/decorators/flask_decorators.py
- samples/flask_authentication.py
1. Add Flask full authentication decorator 
2. Improve descope_validate_auth decorator to support roles
> 1. Add Flask full authentication decorator and improve descope_validate_auth decorator to support roles

- descope/auth.py
- descope/management/user.py
- tests/management/test_user.py
- tests/test_auth.py
https://github.com/descope/etc/issues/2585
Use the correct http method.
> Fix deletion of test user

- descope/auth.py
- tests/test_auth.py
https://github.com/descope/etc/issues/2585
Should be sms and not phone
> Fix sms delivery method

- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
Option to update only a specific attribute
Option to update only user picture
related to https://github.com/descope/etc/issues/2448
+ tests
> Update user properties

- README.md
- descope/management/common.py
- descope/management/sso_settings.py
- samples/management/sso_sample_app.py
- tests/management/test_sso_settings.py
Add method to get SSO settings.
https://github.com/descope/etc/issues/2519
https://github.com/descope/etc/issues/1090
> Add method to get SSO settings

- README.md
- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
add user management functions to set password and expire password according to management descope API
> Add set and expire password

- .vscode/settings.json
- descope/auth.py
- descope/management/sso_settings.py
- tests/management/test_sso_settings.py
- tests/management/test_user.py
- tests/test_auth.py
related to https://github.com/descope/etc/issues/2700
+ test
> Delete SAML settings

- README.md
https://github.com/descope/etc/issues/2293
| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |
A few sentences describing the overall goals of the pull request's commits.
> Fixed go syntax in python sdk readme

- README.md
- descope/management/audit.py
- descope/management/common.py
- descope/mgmt.py
- samples/management/audit_sample_app.py
- tests/management/test_audit.py
Related to  https://github.com/descope/etc/issues/2923
Allow search on audit
> added search on audit

- .vscode/settings.json
- descope/management/user.py
- tests/management/test_user.py
related to https://github.com/descope/etc/issues/2455
+ tests
> Update verified state

- .vscode/settings.json
- README.md
- descope/management/common.py
- descope/management/tenant.py
- samples/management/tenant_sample_app.py
- tests/management/test_tenant.py
Related to: https://github.com/descope/etc/issues/3248
Add option to load tenant by ID.
> Add option to load tenant by ID

- descope/management/user.py
- tests/management/test_user.py
+ test
related to https://github.com/descope/etc/issues/3470
> Search by user status

- README.md
- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
related to https://github.com/descope/etc/issues/2288
> Generate an embedded token for user

- .vscode/settings.json
- README.md
- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
This reverts commit b5448834bb71cd93fe62f9b4890400d15c45159c.
> Revert "Revert embedded link (#262)"

- .vscode/settings.json
- README.md
- descope/authmethod/password.py
- tests/test_password.py
related to https://github.com/descope/etc/issues/3800
Change `password.replace(...)` return value with authentication info
> Replace password session

- descope/management/user.py
- tests/management/test_user.py
+ test 
related to https://github.com/descope/etc/issues/3834
> Create and invite with verified attributes

- README.md
- descope/auth.py
- descope/authmethod/enchantedlink.py
- descope/authmethod/magiclink.py
- descope/authmethod/otp.py
- descope/authmethod/password.py
- descope/authmethod/totp.py
- descope/authmethod/webauthn.py
- descope/descope_client.py
Add optional audience param to validation functions so we can validate token which include the 'aud' claim.
> Add optional audience param to validation functions

- .vscode/settings.json
- README.md
- descope/management/user.py
- tests/management/test_user.py
related to https://github.com/descope/etc/issues/4090
+ tests
> Support invite URL from SDK

- descope/management/user.py
- tests/management/test_user.py
+ test 
related to https://github.com/descope/etc/issues/4154
> Search users by phone or emails

- descope/auth.py
fixes https://github.com/descope/python-sdk/pull/193
fixes https://github.com/descope/etc/issues/2586
Catch specific exception types
Removed places where exceptions thrown from `_validate_token` were encapsulated, this ensures the callers knows exactly why the token failed validation.
> fix: do not catch generic exception

- README.md
- descope/management/common.py
- descope/management/tenant.py
- tests/management/test_tenant.py
By name, attributes, domain,  create tenant with custom attributes 
related to https://github.com/descope/etc/issues/4129
related to https://github.com/descope/etc/issues/3631
+ tests
> Tenant search

- README.md
> Update README.md - Embedded links

- README.md
- descope/management/common.py
- descope/management/project.py
- descope/mgmt.py
- tests/management/test_project.py
https://github.com/descope/etc/issues/4524
expose clone project
also added update-name functionality
> expose clone project

- README.md
- descope/management/authz.py
- descope/management/common.py
- descope/mgmt.py
- samples/management/authz_sample_app.py
- samples/management/files.json
- tests/management/test_authz.py
Added support for ReBAC authz management APIs
> Added authz support for mgmt

- README.md
- descope/management/project.py
Improve clone project comment to mention that this action is supported only with pro license or above
> improve clone project comment

- README.md
- descope/descope_client.py
- tests/test_descope_client.py
https://github.com/descope/etc/issues/4847
expose functions to get matched roles / permissions
> Get matched roles and permissions

- descope/auth.py
- descope/common.py
- descope/management/user.py
- tests/test_auth.py
Add embedded delivery method
fixes: https://github.com/descope/etc/issues/5082
> Add embedded delivery method

- README.md
- descope/management/sso_settings.py
- samples/management/sso_sample_app.py
- tests/management/test_sso_settings.py
Related to https://github.com/descope/etc/issues/4444
Depends on https://github.com/descope/managementservice/pull/686
Makes the tenant domain field be an array of values instead of just one.
> 🚧 Tenant Multi Domain

- .gitignore
- README.md
- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
Fixes https://github.com/descope/etc/issues/5133
Add support for users batch invite
> Add users invite batch support

- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
- Add `remove_all_passkeys` user management API
- Add `delete_by_user_id` user management API
> Management SDK additions

- descope/management/project.py
> Fix comment

- README.md
- descope/management/common.py
- descope/management/flow.py
- descope/management/sso_settings.py
- tests/management/test_flow.py
https://github.com/descope/etc/issues/5360
Add the ability to delete flows by IDs
> Add the ability to delete flows

- README.md
- descope/management/authz.py
- descope/management/common.py
- tests/management/test_authz.py
Expose get_modified to return the modified targets and resources since given date
> Expose Authz get_modified

- README.md
- descope/authmethod/sso.py
- descope/common.py
- descope/descope_client.py
- samples/sso_sample_app.py
- tests/test_descope_client.py
- tests/test_sso.py
saml auth method is deprecated (we keep it for backward compatibility)
> Add sso auth method (instead of saml)

- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
Add text and sort options to users search
> Add text and sort options to users search

- README.md
- descope/management/common.py
- descope/management/project.py
- tests/management/test_project.py
- Add support for import/export project
- Updated README
> Add support for import/export project

- descope/management/user.py
- descope/management/user_pwd.py
- tests/management/test_user.py
- Add support for creating users with cleartext and prehashed passwords
> Add support for creating users with cleartext and prehashed passwords

- descope/__init__.py
- descope/management/user.py
- descope/management/user_pwd.py
- tests/management/test_user.py
Fixes <link_to_github_issue>
| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |
A few sentences describing the overall goals of the pull request's commits.
> Need to address hashed password changes for batch invite

- README.md
- descope/management/access_key.py
- tests/management/test_access_key.py
related to https://github.com/descope/etc/issues/4312
> Option to bind access key to user

- descope/auth.py
- descope/common.py
- tests/test_auth.py
https://github.com/descope/etc/issues/5226#event-11411420436
- Extract region from project ID
-   [x] Tests
-   [x] Documentation (if applicable)
> Extract region from project ID

- README.md
- descope/management/role.py
- tests/management/test_role.py
+ tests
+ readme 
related to https://github.com/descope/etc/issues/2563
> Tenant level roles

- README.md
- descope/management/audit.py
- descope/management/common.py
- samples/management/audit_sample_app.py
- samples/management/authz_sample_app.py
- tests/management/test_audit.py
Add the ability to create audit event
> Audit create event

- descope/management/user.py
- tests/management/test_user.py
Related to: https://github.com/descope/etc/issues/6651
Add support for TOTP seed in invite users.
> Add support for TOTP seed in invite users

- README.md
- descope/auth.py
- descope/management/common.py
- descope/management/user.py
- tests/management/test_user.py
Related to https://github.com/descope/etc/issues/6646
Adds patch user
> Add Patch Users

- README.md
- descope/management/access_key.py
- tests/management/test_access_key.py
Related to https://github.com/descope/etc/issues/6798
Adds Permitted IPs to Access Keys
> Adds Permitted IPs to Access Keys

- descope/management/tenant.py
- tests/management/test_tenant.py
Add some tests for the created time field to load tenant
> add created time field to load tenant

- descope/management/common.py
Use v2 end point instead of deprecated v1
> Search users on v2 api

- .vscode/settings.json
- descope/auth.py
allow for refresh token to be empty
discovered in nightly tests https://github.com/descope/python-sdk/actions/runs/11699503317/job/32581621406
> fix(typing): minor typing fix

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- README.md
- poetry.lock
- pyproject.toml
- requirements.txt
- tox.ini
Fixes https://github.com/descope/etc/issues/8209
Dropping support for python 3.7
> feat!: drop support for python 3.7

- README.md
- descope/common.py
- descope/descope_client.py
- tests/test_descope_client.py
https://github.com/descope/etc/issues/8242
This new function call, will expire all jwts created prior to the one in the request.
> Logout previous sessions

- README.md
- descope/management/common.py
- descope/management/fga.py
- descope/mgmt.py
- tests/management/test_fga.py
This pull request introduces support for Fine-Grained Authorization (FGA) in the Descope SDK. The changes include adding new endpoints, data structures, and methods for managing FGA schemas and relations, as well as performing checks.
Added 4 new functions under `mgmt.fga`
SaveSchema - Creates a new schema for the project.
CreateRelations - Creates new relations for the project.
DeleteRelations - Deletes relations for the project.
Check - Checks if the given relations are satisfied.
> Add FGA APIs

- README.md
- descope/management/jwt.py
- tests/management/test_jwt.py
And with selected tenant
related to https://github.com/descope/etc/issues/8724
> Impersonate with custom claims

- .vscode/settings.json
- pyproject.toml
updating dev major version so package can be installed directly from git alongside other packages that depend on this sdk from git (like django-sdk)
> chore: update dev version

- README.md
related to https://github.com/descope/etc/issues/9390
> add invite url example to readme

- README.md
related to https://github.com/descope/etc/issues/9482
> remove totp seed to readme

- descope/management/user.py
- tests/management/test_user.py
Return user response in update/patch user
> Return user response in update/patch user

- descope/management/sso_settings.py
- tests/management/test_sso_settings.py
https://github.com/descope/etc/issues/8307
Default SSO roles support
> Default SSO roles support

- descope/management/role.py
so now all roles available on tenant are loadable in single request
related to https://github.com/descope/etc/issues/10155
> Add more options to role search

- descope/management/user.py
- tests/management/test_user.py
related to https://github.com/descope/etc/issues/10001
+ test
> Invite with specific user status

- descope/auth.py
- tests/management/test_access_key.py
- tests/management/test_audit.py
- tests/management/test_authz.py
- tests/management/test_fga.py
- tests/management/test_flow.py
- tests/management/test_group.py
- tests/management/test_jwt.py
- tests/management/test_permission.py
- tests/management/test_project.py
- tests/management/test_role.py
- tests/management/test_sso_application.py
- tests/management/test_sso_settings.py
- tests/management/test_tenant.py
- tests/management/test_user.py
- tests/test_auth.py
- tests/test_descope_client.py
- tests/test_enchantedlink.py
- tests/test_magiclink.py
- tests/test_oauth.py
- tests/test_otp.py
- tests/test_password.py
- tests/test_saml.py
- tests/test_sso.py
- tests/test_totp.py
- tests/test_webauthn.py
https://github.com/descope/etc/issues/10013
Add descope project ID header
> Add descope project ID header

- .gitleaksignore
Related to https://github.com/descope/etc/issues/11531
> Add two lines to gitleaks ignore as they are not really a secret
